# Generated by Django 2.1.7 on 2019-03-08 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='avatar.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='condition',
            field=models.CharField(help_text='Brief statement of present condition, less than 50 characters', max_length=50),
        ),
    ]
