# Generated by Django 2.1.7 on 2019-03-08 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20190308_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='buyer_id',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
