# Generated by Django 2.1.7 on 2019-03-09 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_item_buyer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='buy_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
