# Generated by Django 2.1.7 on 2019-03-09 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_item_buy_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='buyer_address',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='buyer_username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
