# Generated by Django 2.1.7 on 2019-03-09 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20190309_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='prev_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
