# Generated by Django 2.1.7 on 2019-03-09 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_item_date_added'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='date_added',
            new_name='created_time',
        ),
    ]
