# Generated by Django 2.1.7 on 2019-03-09 21:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20190310_0303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='created_time',
        ),
        migrations.AddField(
            model_name='item',
            name='created_datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
