# Generated by Django 2.1.7 on 2019-03-09 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20190310_0306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='created_datetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
