# Generated by Django 2.1.7 on 2019-03-09 21:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20190310_0319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='created_datetime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
